<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>

<meta name="Description" content="Imbibe Cocktal Database" />
<meta name="Keywords" content="Cocktails, Drinks" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="Distribution" content="Global" />
<meta name="Robots" content="index,follow" />

<link rel="stylesheet" href="images/prototype.css" type="text/css" />

<title>Imbibe</title>
	
</head>

<body>

<!-- wrap starts here -->
<div id="wrap">

	<div id="header">		
		
		<div id="logo-box">		
			<h1 id="logo"><a href="index.html" title="">Imbibe</a></h1>	
			<h2 id="slogan">I drink, therefore I am</h2>		
		</div>				
				
		<div class="headerphoto"></div>
	
	</div>
	
	<!-- note to self - update this so id="current" functions -->
	<div id="menu">
		<ul>
			<li><a href="index.php">Home</a></li>  
			<li><a href="weeklycocktail.php">Cocktail of the Week</a></li>
		</ul>

	</div>
